### ISSUE TITLE
Deps

### ISSUE THREAD

**Issue by QwertyJack** [arpieb/corenlp#1]
Now the deps is
```
httpoison ~> 0.11
poison ~> 3.1
```
where `httpoison` is out of date while `poison` is too new compared with other mix packages, such as `phoenix`.

**Comment by arpieb** [comment]
Thanks for the heads up, looking into updating deps now!

**Comment by arpieb** [comment]
Done, thanks for the heads-up!

**Comment by QwertyJack** [comment]
@arpieb 
Happy to hear that !
To my surprise, I wonder why not using `httposion 0.13`.
